/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 new.glb 
*/
import { useEffect, useRef, useState } from 'react'
import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function New({ onDisplayClick, ...props }) {
  const { nodes, materials } = useGLTF('/models/new.glb')
  const displayImageTexture = useTexture('/images/alt2.png')
  const IMAGE_ROTATION_DEG = 270
  const soundRef = useRef(null)
  const [audioStarted, setAudioStarted] = useState(false)

  useEffect(() => {
    const sound = new Audio('/new.mp3')
    sound.loop = true
    sound.volume = 0.6
    sound.preload = 'auto'
    soundRef.current = sound

    return () => {
      sound.pause()
      sound.currentTime = 0
      soundRef.current = null
    }
  }, [])

  useEffect(() => {
    displayImageTexture.flipY = false
    displayImageTexture.center.set(0.5, 0.5)
    displayImageTexture.rotation = (IMAGE_ROTATION_DEG * Math.PI) / 180
    displayImageTexture.needsUpdate = true
  }, [displayImageTexture])

  const handleClick = () => {
    if (soundRef.current && !audioStarted) {
      soundRef.current.play().catch(() => {
        // Playback can be blocked by browser policy if gesture detection fails.
      })
      setAudioStarted(true)
    }
  }
  return (
    <group {...props} dispose={null} onClick={handleClick}>
      <mesh geometry={nodes.Cube045.geometry} material={materials['wooden deck']} position={[61.531, 67.151, -3.123]} rotation={[-Math.PI, 0, 0]} scale={[-14.442, -0.384, -0.76]} />
      <group position={[36.662, 83.883, -21.224]} scale={[0.374, 3.372, 0.277]}>
        <mesh geometry={nodes.Cube015_1.geometry} material={materials['wooden pole']} />
        <mesh geometry={nodes.Cube015_2.geometry} material={materials['wooden plank']} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials.metal} position={[8.776, 96.374, -8.955]} scale={[0.865, 0.206, 0.865]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.metal} position={[8.776, 94.652, -8.955]} scale={[0.865, 0.206, 0.865]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Material} position={[8.776, 95.509, -8.955]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.684, -0.826, -0.684]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.metal} position={[8.776, 96.605, -8.955]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.437, -0.225, -0.437]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.metal} position={[8.776, 97.242, -8.955]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.209, -0.995, -0.209]} />
      <mesh geometry={nodes.Cube046.geometry} material={materials['wooden pole']} position={[6.054, 98.237, -8.997]} rotation={[-Math.PI, 0, 0]} scale={[-3.775, -0.39, -0.39]} />
      <mesh geometry={nodes.Cube047.geometry} material={materials['wooden pole']} position={[2.46, 91.273, -8.997]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[-8.526, -0.39, -0.476]} />
      <mesh geometry={nodes.Cube048.geometry} material={materials['wooden pole']} position={[4.38, 96.413, -8.997]} rotation={[3.022, 0.128, -0.759]} scale={[-2.419, -0.25, -0.25]} />
      <mesh geometry={nodes.Cube049.geometry} material={materials.metal} position={[8.783, 98.237, -8.997]} rotation={[-Math.PI, 0, 0]} scale={[-0.427, -0.523, -0.523]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials.metal} position={[73.68, 80.002, -22.614]} rotation={[0, -Math.PI / 2, 0]} scale={[0.865, 0.206, 0.865]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials.metal} position={[73.68, 78.281, -22.614]} rotation={[0, -Math.PI / 2, 0]} scale={[0.865, 0.206, 0.865]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials.Material} position={[73.68, 79.138, -22.614]} rotation={[0, Math.PI / 2, 0]} scale={[-0.684, -0.826, -0.684]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials.metal} position={[73.68, 80.234, -22.614]} rotation={[0, Math.PI / 2, 0]} scale={[-0.437, -0.225, -0.437]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials.metal} position={[73.68, 80.871, -22.614]} rotation={[0, Math.PI / 2, 0]} scale={[-0.209, -0.995, -0.209]} />
      <mesh geometry={nodes.Cube051.geometry} material={materials['wooden pole']} position={[73.722, 81.866, -25.336]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[-3.775, -0.39, -0.39]} />
      <mesh geometry={nodes.Cube052.geometry} material={materials['wooden pole']} position={[73.722, 75.435, -28.931]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[-8.526, -0.39, -0.476]} />
      <mesh geometry={nodes.Cube053.geometry} material={materials['wooden pole']} position={[73.722, 80.042, -27.01]} rotation={[0.747, 1.395, 1.628]} scale={[-2.419, -0.25, -0.25]} />
      <mesh geometry={nodes.Cube054.geometry} material={materials.metal} position={[73.722, 81.866, -22.607]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[-0.427, -0.523, -0.523]} />
      <group position={[73.177, 68.339, -0.96]} rotation={[0, -Math.PI / 2, 0]} scale={[0.374, 3.372, 0.277]}>
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['wooden pole']} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials['wooden plank']} />
      </group>
      <mesh geometry={nodes.Cylinder010.geometry} material={materials.metal} position={[76.756, 64.622, 21.623]} rotation={[0, -Math.PI / 2, 0]} scale={[0.865, 0.206, 0.865]} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials.metal} position={[76.756, 62.9, 21.623]} rotation={[0, -Math.PI / 2, 0]} scale={[0.865, 0.206, 0.865]} />
      <mesh geometry={nodes.Cylinder012.geometry} material={materials.Material} position={[76.756, 63.757, 21.623]} rotation={[0, Math.PI / 2, 0]} scale={[-0.684, -0.826, -0.684]} />
      <mesh geometry={nodes.Cylinder013.geometry} material={materials.metal} position={[76.756, 64.853, 21.623]} rotation={[0, Math.PI / 2, 0]} scale={[-0.437, -0.225, -0.437]} />
      <mesh geometry={nodes.Cylinder014.geometry} material={materials.metal} position={[76.756, 65.49, 21.623]} rotation={[0, Math.PI / 2, 0]} scale={[-0.209, -0.995, -0.209]} />
      <mesh geometry={nodes.Cube056.geometry} material={materials['wooden pole']} position={[76.798, 66.485, 18.902]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[-3.775, -0.39, -0.39]} />
      <mesh geometry={nodes.Cube057.geometry} material={materials['wooden pole']} position={[76.798, 60.054, 15.307]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[-8.526, -0.39, -0.476]} />
      <mesh geometry={nodes.Cube058.geometry} material={materials['wooden pole']} position={[76.798, 64.662, 17.227]} rotation={[0.747, 1.395, 1.628]} scale={[-2.419, -0.25, -0.25]} />
      <mesh geometry={nodes.Cube059.geometry} material={materials.metal} position={[76.798, 66.485, 21.631]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[-0.427, -0.523, -0.523]} />
      <mesh geometry={nodes.Cylinder015.geometry} material={materials.metal} position={[61.082, 64.622, 21.623]} rotation={[0, -Math.PI / 2, 0]} scale={[0.865, 0.206, 0.865]} />
      <mesh geometry={nodes.Cylinder016.geometry} material={materials.metal} position={[61.082, 62.9, 21.623]} rotation={[0, -Math.PI / 2, 0]} scale={[0.865, 0.206, 0.865]} />
      <mesh geometry={nodes.Cylinder017.geometry} material={materials.Material} position={[61.082, 63.757, 21.623]} rotation={[0, Math.PI / 2, 0]} scale={[-0.684, -0.826, -0.684]} />
      <mesh geometry={nodes.Cylinder018.geometry} material={materials.metal} position={[61.082, 64.853, 21.623]} rotation={[0, Math.PI / 2, 0]} scale={[-0.437, -0.225, -0.437]} />
      <mesh geometry={nodes.Cylinder019.geometry} material={materials.metal} position={[61.082, 65.49, 21.623]} rotation={[0, Math.PI / 2, 0]} scale={[-0.209, -0.995, -0.209]} />
      <mesh geometry={nodes.Cube060.geometry} material={materials['wooden pole']} position={[61.124, 66.485, 18.902]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[-3.775, -0.39, -0.39]} />
      <mesh geometry={nodes.Cube061.geometry} material={materials['wooden pole']} position={[61.124, 60.054, 15.307]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[-8.526, -0.39, -0.476]} />
      <mesh geometry={nodes.Cube062.geometry} material={materials['wooden pole']} position={[61.124, 64.662, 17.227]} rotation={[0.747, 1.395, 1.628]} scale={[-2.419, -0.25, -0.25]} />
      <mesh geometry={nodes.Cube063.geometry} material={materials.metal} position={[61.124, 66.485, 21.631]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[-0.427, -0.523, -0.523]} />
      <group position={[-13.53, 96.698, 47.664]} scale={[6.376, 12.036, 6.376]}>
        <mesh geometry={nodes.Cylinder020_1.geometry} material={materials.leafs} />
        <mesh geometry={nodes.Cylinder020_2.geometry} material={materials['wooden pole']} />
      </group>
      <group position={[44.932, 88.771, 11.31]} rotation={[0, 0.305, 0]} scale={[6.829, 9.515, 6.829]}>
        <mesh geometry={nodes.Cylinder026_1.geometry} material={materials.leafs} />
        <mesh geometry={nodes.Cylinder026_2.geometry} material={materials['wooden pole']} />
      </group>
      <group position={[4.664, 90.785, 42.029]} scale={[6.615, 9.394, 6.615]}>
        <mesh geometry={nodes.Cylinder027_1.geometry} material={materials.leafs} />
        <mesh geometry={nodes.Cylinder027_2.geometry} material={materials['wooden pole']} />
      </group>
      <group position={[-2.524, 74.62, 54.682]} scale={[3.968, 5.634, 3.968]}>
        <mesh geometry={nodes.Cylinder028_1.geometry} material={materials.leafs} />
        <mesh geometry={nodes.Cylinder028_2.geometry} material={materials['wooden pole']} />
      </group>
      <group position={[34.415, 83.701, -47.037]} scale={[6.615, 7.793, 6.615]}>
        <mesh geometry={nodes.Cylinder029_1.geometry} material={materials.leafs} />
        <mesh geometry={nodes.Cylinder029_2.geometry} material={materials['wooden pole']} />
      </group>
      <group position={[20.372, 97.231, -55.73]} scale={[9.376, 11.095, 9.376]}>
        <mesh geometry={nodes.Cylinder030_1.geometry} material={materials.leafs} />
        <mesh geometry={nodes.Cylinder030_2.geometry} material={materials['wooden pole']} />
      </group>
      <group position={[-2.656, 106.778, -47.195]} scale={[8.158, 14.063, 8.158]}>
        <mesh geometry={nodes.Cylinder031_1.geometry} material={materials.leafs} />
        <mesh geometry={nodes.Cylinder031_2.geometry} material={materials['wooden pole']} />
      </group>
      <group position={[-44.233, 95.984, 13.209]} scale={[8.158, 11.105, 8.158]}>
        <mesh geometry={nodes.Cylinder032_1.geometry} material={materials.leafs} />
        <mesh geometry={nodes.Cylinder032_2.geometry} material={materials['wooden pole']} />
      </group>
      <group position={[-39.134, 89.104, 40.273]} scale={[8.158, 9.414, 8.158]}>
        <mesh geometry={nodes.Cylinder033_1.geometry} material={materials.leafs} />
        <mesh geometry={nodes.Cylinder033_2.geometry} material={materials['wooden pole']} />
      </group>
      <mesh geometry={nodes.land1.geometry} material={materials.island} position={[26.097, 45.375, 10.087]} scale={78.74} />
      <mesh geometry={nodes.land2.geometry} material={materials['island down']} position={[26.097, 41.755, 10.087]} rotation={[0, 0.083, 0]} scale={84.099} />
      <mesh geometry={nodes.Pond.geometry} material={materials.water} position={[27.812, 50.885, 59.785]} scale={[24.07, 1, 14.283]} />
      <mesh geometry={nodes.Cylinder021.geometry} material={materials['wooden pilll']} position={[63.521, 59.298, -16.361]} scale={[5.272, 7.746, 5.272]} />
      <mesh geometry={nodes.Cylinder022.geometry} material={materials['wooden pilll']} position={[63.521, 75.189, -16.361]} rotation={[0, 0.388, 0]} scale={[4.189, 8.386, 4.189]} />
      <mesh geometry={nodes.Cylinder023.geometry} material={materials['wooden pilll']} position={[83.368, 55.318, -22.795]} scale={4.308} />
      <mesh geometry={nodes.Cylinder024.geometry} material={materials.rock} position={[-7.186, 66.696, 0.759]} scale={[26.752, 15.772, 32.446]} />
      <mesh geometry={nodes.Cylinder025.geometry} material={materials['wooden pilll']} position={[-29.815, 79.276, -29.592]} scale={[8.727, 29.041, 10.585]} />
      <mesh geometry={nodes.Cylinder034.geometry} material={materials['wooden pilll']} position={[11.921, 55.318, 78.415]} rotation={[0, -0.743, 0]} scale={4.152} />
      <mesh geometry={nodes.Cylinder035.geometry} material={materials['wooden pilll']} position={[-12.471, 55.201, 69.676]} rotation={[0, -0.743, 0]} scale={4.152} />
      <mesh geometry={nodes.Icosphere.geometry} material={materials.rock} position={[30.594, -2.462, 36.677]} scale={6.348} />
      <mesh geometry={nodes.Icosphere001.geometry} material={materials.rock} position={[25.485, 21.398, 52.663]} scale={[4.596, 3.443, 3.58]} />
      <mesh geometry={nodes.Icosphere002.geometry} material={materials.rock} position={[40.772, -8.341, 33.28]} scale={[6.168, 7.045, 6.407]} />
      <mesh geometry={nodes.Cube064.geometry} material={materials.water} position={[23.93, -5.659, 7.971]} scale={[307.097, 49.136, 307.097]} />
      <mesh geometry={nodes.Cube065.geometry} material={materials['stone payment']} position={[68.89, 49.517, 25.404]} scale={[3.503, 2.969, 2.989]} />
      <mesh geometry={nodes.Cube066.geometry} material={materials['stone payment']} position={[78.603, 49.517, 25.404]} scale={[4.96, 2.969, 2.927]} />
      <mesh geometry={nodes.Cube067.geometry} material={materials['stone payment']} position={[59.269, 49.517, 25.404]} scale={[4.96, 2.969, 3.116]} />
      <mesh geometry={nodes.Cube068.geometry} material={materials['stone payment']} position={[65.713, 49.517, 32.575]} scale={[4.96, 2.969, 3.116]} />
      <mesh geometry={nodes.Cube069.geometry} material={materials['stone payment']} position={[75.789, 49.517, 32.484]} scale={[3.503, 2.969, 2.989]} />
      <mesh geometry={nodes.Cube070.geometry} material={materials['stone payment']} position={[57.726, 49.517, 31.304]} scale={[1.682, 2.969, 1.852]} />
      <mesh geometry={nodes.Cube071.geometry} material={materials['stone payment']} position={[67.477, 49.517, 38.493]} scale={[1.682, 2.969, 1.852]} />
      <mesh geometry={nodes.Cube072.geometry} material={materials['stone payment']} position={[62.809, 49.517, 38.384]} scale={[1.682, 2.969, 1.852]} />
      <mesh geometry={nodes.Cube073.geometry} material={materials['stone payment']} position={[56.274, 49.517, 39.019]} rotation={[0, -Math.PI / 2, 0]} scale={[4.96, 2.969, 3.116]} />
      <mesh geometry={nodes.Cube074.geometry} material={materials['stone payment']} position={[64.862, 49.517, 42.806]} scale={[1.682, 2.969, 1.852]} />
      <mesh geometry={nodes.Icosphere003.geometry} material={materials.rock} position={[25.882, 31.505, 49.947]} rotation={[-0.058, -0.38, -0.267]} scale={[2.958, 2.216, 2.305]} />
      <mesh geometry={nodes.Icosphere004.geometry} material={materials.rock} position={[1.266, 23.213, 65.703]} scale={[4.187, 3.137, 3.262]} />
      <mesh geometry={nodes.Icosphere005.geometry} material={materials.rock} position={[0.593, 37.27, 62.986]} rotation={[-0.166, -0.394, -0.4]} scale={[2.401, 1.799, 1.871]} />
      <mesh geometry={nodes.Icosphere006.geometry} material={materials.rock} position={[40.388, 12.335, 38.454]} rotation={[0.073, -0.672, 0]} scale={[4.031, 4.604, 4.187]} />
      <mesh geometry={nodes.Icosphere007.geometry} material={materials.rock} position={[-28.85, 20.84, 59.778]} rotation={[0, 0, -0.792]} scale={[4.213, 5.138, 3.694]} />
      <mesh geometry={nodes.Icosphere008.geometry} material={materials.rock} position={[90.772, 29.228, 57.472]} rotation={[-1.148, 0, 0]} scale={[5.783, 6.443, 5.237]} />
      <mesh geometry={nodes.Icosphere009.geometry} material={materials.rock} position={[76.08, 33.248, 52.154]} rotation={[-1.126, 0.308, -0.144]} scale={[4.893, 5.452, 4.432]} />
      <mesh geometry={nodes.Icosphere010.geometry} material={materials.rock} position={[86.074, 43.555, 30.884]} rotation={[-1.126, 0.308, -0.144]} scale={[2.193, 2.443, 1.986]} />
      <mesh geometry={nodes.Icosphere011.geometry} material={materials.rock} position={[79.209, -15.838, 220.361]} rotation={[-1.148, 0, 0]} scale={[14.023, 15.623, 12.699]} />
      <mesh geometry={nodes.Icosphere012.geometry} material={materials.rock} position={[96.557, -0.621, 170.919]} rotation={[-1.176, 0.156, 0.357]} scale={[9.499, 10.583, 8.602]} />
      <mesh geometry={nodes.Icosphere013.geometry} material={materials.rock} position={[144.889, 2.966, 107.369]} rotation={[-1.176, 0.156, 0.357]} scale={[9.499, 10.583, 8.602]} />
      <mesh geometry={nodes.Icosphere014.geometry} material={materials.rock} position={[177.81, -33.44, 234.481]} rotation={[-1.218, 0.156, 0.357]} scale={[18.122, 21.748, 22.654]} />
      <mesh geometry={nodes.Cube076.geometry} material={materials['Wooden window']} position={[49.742, 65.829, 49.966]} scale={[0.835, 6.352, 12.836]} />
      <mesh geometry={nodes.Cube077.geometry} material={materials['wooden pilll']} position={[49.238, 60.593, 41.446]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.539, -12.886, -0.539]} />
      <mesh geometry={nodes.Cube075.geometry} material={materials['wooden pilll']} position={[49.238, 60.593, 57.991]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.539, -12.886, -0.539]} />
      <mesh geometry={nodes.display.geometry} position={[50.224, 65.888, 50.033]} rotation={[0, 0, -Math.PI / 2]} scale={[5.622, 7.389, 12.218]}
        onClick={(e) => { e.stopPropagation(); onDisplayClick?.() }}
      >
        <meshBasicMaterial map={displayImageTexture} toneMapped={false} />
      </mesh>
      <group position={[0, 85.446, 10.549]} scale={[0.28, 1, 6]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['wooden plank']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['wooden pole']} />
      </group>
      <group position={[-19.067, 85.446, 17.002]} rotation={[0, -1.571, 0]} scale={[0.28, 1, 5.075]}>
        <mesh geometry={nodes.Cube007_1.geometry} material={materials['wooden plank']} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials['wooden pole']} />
      </group>
      <group position={[-24.538, 85.446, 0.345]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.28, 1, 6]}>
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['wooden plank']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials['wooden pole']} />
      </group>
      <group position={[-5.404, 85.446, -6.057]} rotation={[0, 1.571, 0]} scale={[0.28, 1, 5.075]}>
        <mesh geometry={nodes.Cube011_1.geometry} material={materials['wooden plank']} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials['wooden pole']} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials['wooden pole']} position={[-12.323, 83.352, 5.427]} scale={[13.554, 0.478, 12.893]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['wooden pole']} position={[-12.323, 96.251, 5.427]} scale={[13.554, 0.478, 12.893]} />
      <group position={[-1.308, 96.138, 10.005]} scale={[0.25, 0.893, 5.36]}>
        <mesh geometry={nodes.Cube050_1.geometry} material={materials['wooden plank']} />
        <mesh geometry={nodes.Cube050_2.geometry} material={materials['wooden pole']} />
      </group>
      <group position={[-18.341, 96.138, 15.77]} rotation={[0, -1.571, 0]} scale={[0.25, 0.893, 4.533]}>
        <mesh geometry={nodes.Cube051_1.geometry} material={materials['wooden plank']} />
        <mesh geometry={nodes.Cube051_2.geometry} material={materials['wooden pole']} />
      </group>
      <group position={[-23.229, 96.138, 0.89]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.25, 0.893, 5.36]}>
        <mesh geometry={nodes.Cube052_1.geometry} material={materials['wooden plank']} />
        <mesh geometry={nodes.Cube052_2.geometry} material={materials['wooden pole']} />
      </group>
      <group position={[-6.136, 96.138, -4.829]} rotation={[0, 1.571, 0]} scale={[0.25, 0.893, 4.533]}>
        <mesh geometry={nodes.Cube053_1.geometry} material={materials['wooden plank']} />
        <mesh geometry={nodes.Cube053_2.geometry} material={materials['wooden pole']} />
      </group>
      <mesh geometry={nodes.Wooden_Wall009.geometry} material={materials['wooden plank']} position={[-22.497, 106.395, -1.377]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.28, 1, 5.075]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials['wooden pole']} position={[-12.209, 106.289, 5.366]} rotation={[0, -Math.PI / 2, 0]} scale={[11.535, 0.44, 11.198]} />
      <group position={[-16.622, 84.573, -4.899]} rotation={[0, -Math.PI / 2, 0]} scale={[0.25, 0.893, 5.36]}>
        <mesh geometry={nodes.Cube030_1.geometry} material={materials['wooden plank']} />
        <mesh geometry={nodes.Cube030_2.geometry} material={materials['wooden pole']} />
      </group>
      <group position={[-20.248, 84.283, -18.413]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.2, 0.717, 3.638]}>
        <mesh geometry={nodes.Cube031_1.geometry} material={materials['wooden plank']} />
        <mesh geometry={nodes.Cube031_2.geometry} material={materials['wooden pole']} />
      </group>
      <group position={[-8.307, 84.283, -22.336]} rotation={[0, 1.571, 0]} scale={[0.2, 0.717, 4.301]}>
        <mesh geometry={nodes.Cube036_1.geometry} material={materials['wooden plank']} />
        <mesh geometry={nodes.Cube036_2.geometry} material={materials['wooden pole']} />
      </group>
      <group position={[-3.717, 84.283, -8.619]} scale={[0.2, 0.717, 3.638]}>
        <mesh geometry={nodes.Cube037_1.geometry} material={materials['wooden plank']} />
        <mesh geometry={nodes.Cube037_2.geometry} material={materials['wooden pole']} />
      </group>
      <mesh geometry={nodes.Wooden_Wall014.geometry} material={materials['wooden plank']} position={[-6.488, 92.514, -21.748]} rotation={[0, 1.571, 0]} scale={[0.224, 0.802, 4.072]} />
      <mesh geometry={nodes.Cube025.geometry} material={materials['wooden pole']} position={[-11.899, 92.429, -13.493]} rotation={[-Math.PI, 0, -Math.PI]} scale={[9.257, 0.353, 8.986]} />
      <mesh geometry={nodes.Cube043.geometry} material={materials['wooden pole']} position={[-12.172, 83.303, -12.844]} scale={[10.877, 0.383, 10.346]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Wooden window']} position={[-0.966, 98.328, 5.786]} scale={[0.241, 0.425, 2.956]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.glass} position={[-1.095, 100.66, 5.741]} rotation={[Math.PI, 0, 0]} scale={[0.093, 2.733, 2.076]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Wooden window']} position={[-12.114, 88.01, -6.462]} rotation={[0, Math.PI / 2, 0]} scale={[0.241, 0.425, 2.956]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials.glass} position={[-12.158, 90.342, -6.305]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[0.125, 2.733, 2.076]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Wooden window']} position={[-23.585, 98.328, 5.741]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.241, 0.425, 2.956]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials.glass} position={[-23.428, 100.66, 5.786]} rotation={[0, 0, -Math.PI]} scale={[0.093, 2.733, 2.076]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Wooden window']} position={[-17.151, 98.861, 16.162]} rotation={[0, -1.571, 0]} scale={[0.241, 0.425, 2.956]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials.glass} position={[-17.107, 101.193, 16.005]} rotation={[Math.PI, 1.571, 0]} scale={[0.125, 2.733, 2.076]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Wooden window']} position={[-11.547, 88.01, 17.391]} rotation={[0, -1.571, 0]} scale={[0.241, 0.425, 2.956]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials.glass} position={[-11.502, 90.342, 17.234]} rotation={[Math.PI, 1.571, 0]} scale={[0.125, 2.733, 2.076]} />
      <mesh geometry={nodes.Cube017.geometry} material={materials['Wooden window']} position={[-6.859, 98.861, 16.162]} rotation={[0, -1.571, 0]} scale={[0.241, 0.425, 2.956]} />
      <mesh geometry={nodes.Cube018.geometry} material={materials.glass} position={[-6.815, 101.193, 16.005]} rotation={[Math.PI, 1.571, 0]} scale={[0.125, 2.733, 2.076]} />
      <mesh geometry={nodes.Cube026.geometry} material={materials['Wooden window']} position={[-12.402, 86.763, -4.556]} rotation={[0, -Math.PI / 2, 0]} scale={[0.241, 0.425, 2.956]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials.glass} position={[-12.358, 89.095, -4.713]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.093, 2.733, 2.076]} />
      <mesh geometry={nodes.Cube030.geometry} material={materials['Wooden window']} position={[-3.386, 85.946, -17.073]} scale={[0.194, 0.341, 2.372]} />
      <mesh geometry={nodes.Cube031.geometry} material={materials.glass} position={[-3.512, 87.817, -17.109]} rotation={[Math.PI, 0, 0]} scale={[0.101, 2.193, 1.666]} />
      <mesh geometry={nodes.Cube032.geometry} material={materials['Wooden window']} position={[-12.2, 86.04, -22.622]} rotation={[0, 1.571, 0]} scale={[0.194, 0.341, 2.372]} />
      <mesh geometry={nodes.Cube033.geometry} material={materials.glass} position={[-12.236, 87.912, -22.496]} rotation={[Math.PI, -1.571, 0]} scale={[0.074, 2.193, 1.666]} />
      <mesh geometry={nodes.Cube034.geometry} material={materials['Wooden window']} position={[-20.563, 86.468, -17.459]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.194, 0.341, 2.372]} />
      <mesh geometry={nodes.Cube035.geometry} material={materials.glass} position={[-20.437, 88.34, -17.423]} rotation={[0, 0, -Math.PI]} scale={[0.101, 2.193, 1.666]} />
      <mesh geometry={nodes.Cube036.geometry} material={materials['Wooden window']} position={[-20.563, 87.943, -9.199]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.194, 0.341, 2.372]} />
      <mesh geometry={nodes.Cube037.geometry} material={materials.glass} position={[-20.437, 89.814, -9.163]} rotation={[0, 0, -Math.PI]} scale={[0.101, 2.193, 1.666]} />
      <group position={[0.544, 84.897, 5.934]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.515, 2.908, 0.556]}>
        <mesh geometry={nodes.Cube044_1.geometry} material={materials['Wooden window']} />
        <mesh geometry={nodes.Cube044_2.geometry} material={materials['door handle']} />
      </group>
      <group position={[-12.25, 104.194, -8.12]} rotation={[2.41, 0, Math.PI / 2]} scale={[0.762, 12.398, 0.679]}>
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['wooden pole']} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials['wooden plank']} />
      </group>
      <mesh geometry={nodes.Cube022.geometry} material={materials['wooden pole']} position={[-12.184, 116.402, 5.634]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.997, 12.251, 0.918]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['wooden plank']} position={[-2.099, 110.922, 5.351]} rotation={[0, -Math.PI / 2, 0]} scale={[11.138, 5.18, 0.293]} />
      <mesh geometry={nodes.Cube023.geometry} material={materials['wooden plank']} position={[-12.25, 104.194, -8.12]} rotation={[2.41, 0, Math.PI / 2]} scale={[0.762, 12.398, 0.679]} />
      <mesh geometry={nodes.Cube024.geometry} material={materials['wooden plank']} position={[-12.386, 109.681, 12.092]} rotation={[1.968, -1.568, 2.808]} scale={[0.638, 8.093, 10.468]} />
      <group position={[-1.076, 90.748, -13.525]} rotation={[Math.PI / 2, 0.839, -Math.PI]} scale={[0.612, 9.949, 0.545]}>
        <mesh geometry={nodes.Cube068_1.geometry} material={materials['wooden pole']} />
        <mesh geometry={nodes.Cube068_2.geometry} material={materials['wooden plank']} />
      </group>
      <mesh geometry={nodes.Cube039.geometry} material={materials['wooden pole']} position={[-12.114, 100.544, -13.473]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.8, 9.831, 0.736]} />
      <mesh geometry={nodes.Cube040.geometry} material={materials['wooden plank']} position={[-11.887, 96.147, -5.62]} rotation={[-Math.PI, 0, -Math.PI]} scale={[8.938, 4.157, 0.236]} />
      <mesh geometry={nodes.Cube041.geometry} material={materials['wooden plank']} position={[-1.076, 90.748, -13.525]} rotation={[Math.PI / 2, 0.839, -Math.PI]} scale={[0.612, 9.949, 0.545]} />
      <mesh geometry={nodes.Cube042.geometry} material={materials['wooden plank']} position={[-17.296, 95.151, -13.635]} rotation={[3.139, 0.001, -2.302]} scale={[0.512, 6.494, 8.401]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['wooden deck']} position={[1.424, 83.051, 30.924]} scale={[33.696, 0.416, 1.892]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['wooden pole']} position={[33.22, 86.079, 30.984]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.439, -2.963, -0.439]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['wooden pole']} position={[30.9, 88.14, 30.984]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-0.439, -3.372, -0.182]} />
      <mesh geometry={nodes.Cube028.geometry} material={materials['wooden pole']} position={[30.9, 88.14, -35.705]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-0.439, -3.372, -0.182]} />
      <mesh geometry={nodes.Cube029.geometry} material={materials['wooden pole']} position={[-30.148, 85.996, 29.427]} rotation={[0, Math.PI / 2, 0]} scale={[-0.439, -2.963, -0.45]} />
      <mesh geometry={nodes.Cube044.geometry} material={materials['wooden pole']} position={[-30.148, 88.057, 27.107]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.439, -3.372, -0.186]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['wooden pole']} position={[33.22, 86.079, -35.632]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.439, -2.963, -0.439]} />
    </group>
  )
}

useGLTF.preload('/models/new.glb')
